// Write a managed block of `[profile.release.package.<crate>]` overrides
// into Cargo.toml based on a hot/cold classification. Idempotent: the block
// is delimited by sentinel comments, so re-running replaces it cleanly and
// does not disturb hand-written `[profile.release.package.*]` sections.
//
// Hot crates → opt-level = 3
// Cold crates → opt-level = "z"
//
// We *only* emit overrides whose effective opt-level differs from the
// workspace [profile.release] default (3 today). So:
//   - hot crates are normally a no-op (omitted) since `[profile.release]`
//     already has `opt-level = 3`. We still emit them when the user has
//     manually flipped the workspace default to "s"/"z" globally.
//   - cold crates always emit `opt-level = "z"`.

import { readFileSync, writeFileSync } from "node:fs";
import { argv, env, exit } from "node:process";

import type { ClassifiedCrate } from "./pgo-classify.ts";

export const BEGIN_MARKER = "# >>> pgo-managed-overrides >>>";
export const END_MARKER = "# <<< pgo-managed-overrides <<<";

const BLOCK_RE = new RegExp(
	String.raw`\r?\n?${escapeRe(BEGIN_MARKER)}[\s\S]*?${escapeRe(END_MARKER)}\r?\n?`,
	"m"
);

function escapeRe(s: string): string {
	return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Parse the workspace [profile.release] opt-level. Defaults to "3" if not
 * set or if the section is missing.
 */
export function readWorkspaceReleaseOptLevel(cargoToml: string): string {
	const m = cargoToml.match(
		/^\[profile\.release\]\r?\n([\s\S]*?)(?=^\[)/m
	);
	if (!m) return "3";
	const body = m[1];
	const km = body.match(/^\s*opt-level\s*=\s*(?:"([^"]+)"|(\S+))/m);
	if (!km) return "3";
	return km[1] ?? km[2];
}

export interface RenderOptions {
	workspaceDefault?: string; // override the auto-detected workspace opt-level
	hotOptLevel?: string; // default "3"
	coldOptLevel?: string; // default "\"z\""
}

/**
 * Render the managed block (markers + per-crate sections) for a
 * classification. Returns a string ending in a newline (empty string if no
 * overrides are needed).
 */
export function renderManagedBlock(
	classification: { hot: readonly ClassifiedCrate[]; cold: readonly ClassifiedCrate[] },
	cargoToml: string,
	opts: RenderOptions = {}
): string {
	const wsDefault = opts.workspaceDefault ?? readWorkspaceReleaseOptLevel(cargoToml);
	const hotLevel = opts.hotOptLevel ?? "3";
	const coldLevel = opts.coldOptLevel ?? '"z"';

	const lines: string[] = [];
	lines.push(BEGIN_MARKER);
	lines.push("# Generated by .github/workflows/scripts/pgo-apply-overrides.ts.");
	lines.push("# Do not edit by hand — re-run pgo-run.ts to refresh.");
	lines.push(`# Workspace [profile.release].opt-level detected as ${wsDefault}.`);

	let emittedAny = false;
	const hotsToEmit = wsDefault === hotLevel ? [] : classification.hot;
	for (const c of hotsToEmit) {
		lines.push("");
		lines.push(`[profile.release.package.${c.crate}]`);
		lines.push(`opt-level = ${formatLevel(hotLevel)}  # hot: ${(c.pct * 100).toFixed(2)}% (${c.reason})`);
		emittedAny = true;
	}
	const coldsToEmit = wsDefault === stripQuotes(coldLevel) ? [] : classification.cold;
	for (const c of coldsToEmit) {
		lines.push("");
		lines.push(`[profile.release.package.${c.crate}]`);
		const pct = c.pct > 0 ? `${(c.pct * 100).toFixed(2)}%` : "unsampled";
		lines.push(`opt-level = ${coldLevel}  # cold: ${pct} (${c.reason})`);
		emittedAny = true;
	}
	if (!emittedAny) {
		lines.push("# (no overrides needed — workspace default already matches)");
	}

	lines.push(END_MARKER);
	return lines.join("\n") + "\n";
}

function formatLevel(level: string): string {
	// "3" → 3, "s" → "s", `"z"` already-quoted → keep.
	if (/^\d+$/.test(level)) return level;
	if (level.startsWith('"')) return level;
	return `"${level}"`;
}

function stripQuotes(level: string): string {
	return level.replace(/^"|"$/g, "");
}

/**
 * Replace any existing managed block in Cargo.toml with `block`. If no
 * managed block is present, append `block` to end-of-file with a leading
 * blank line.
 */
export function writeManagedBlock(cargoToml: string, block: string): string {
	if (BLOCK_RE.test(cargoToml)) {
		return cargoToml.replace(BLOCK_RE, "\n" + block);
	}
	const trailingNewline = cargoToml.endsWith("\n") ? "" : "\n";
	return cargoToml + trailingNewline + "\n" + block;
}

/**
 * Remove the managed block (if any) — used by `pgo-run.ts --revert`.
 */
export function removeManagedBlock(cargoToml: string): string {
	return cargoToml.replace(BLOCK_RE, "");
}

/**
 * Apply overrides to a Cargo.toml file on disk.
 */
export function applyOverridesToFile(
	cargoTomlPath: string,
	classification: { hot: readonly ClassifiedCrate[]; cold: readonly ClassifiedCrate[] },
	opts: RenderOptions = {}
): { changed: boolean } {
	const before = readFileSync(cargoTomlPath, "utf8");
	const block = renderManagedBlock(classification, before, opts);
	const after = writeManagedBlock(before, block);
	if (after === before) return { changed: false };
	writeFileSync(cargoTomlPath, after);
	return { changed: true };
}

// --- Script entry point ---

function isMain(): boolean {
	const url = import.meta.url;
	return Boolean(argv[1] && url === `file://${argv[1]}`);
}

if (isMain()) {
	const cargoTomlPath = env.CARGO_TOML ?? "Cargo.toml";
	const profilePath = argv[2];
	if (!profilePath) {
		console.error("Usage: pgo-apply-overrides.ts <profile.json>");
		exit(2);
	}
	import("./pgo-profile.ts").then(async pp => {
		const cls = await import("./pgo-classify.ts");
		const profile = pp.readProfile(profilePath);
		const classification = cls.classify(profile);
		const { changed } = applyOverridesToFile(cargoTomlPath, classification);
		console.log(
			`overrides ${changed ? "updated" : "unchanged"} in ${cargoTomlPath}: ${classification.hot.length} hot, ${classification.cold.length} cold`
		);
	});
}
